// <auto-generated />
namespace ServisTakip.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class delete_gidilenguzergah_toKisi : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(delete_gidilenguzergah_toKisi));
        
        string IMigrationMetadata.Id
        {
            get { return "202201060506385_delete_gidilenguzergah_toKisi"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
